export default {
    logo: "/images/Logo.svg",
    logoFull: "/images/Logo-full.svg",
    home: "/images/Home.svg",
    card: "/images/Card.svg",
    payments: "/images/Payments.svg",
    credit: "/images/Credit.svg",
    account: "/images/Account.svg",
    add: "/images/box.svg",
    visa: "/images/Visa_logo.svg",
    eye: "/images/remove_red_eye.svg",
    freezeCard: "/images/Freeze_card.svg",
    setSpendLimit: "/images/Set_spend_limit.svg",
    gPay: "/images/GPay.svg",
    replaceCard: "/images/Replace_card.svg",
    cancelCard: "/images/Deactivate_card.svg",
    cardDetails: "/images/card_details.svg",
    recentTransactions: "/images/recent_transactions.svg",
    downArrow: "/images/down-arrow.svg",
    upArrow: "/images/down-arrow-1.svg",
    businessAndFinance: "/images/business-and-finance.svg",
    nextCaret: "/images/next.svg",
    fileStorage: "/images/file-storage.svg",
    flights: "/images/flights.svg",
    megaphone: "/images/megaphone.svg"
};